baseURL: http://dparo.github.io
languageCode: en-us
title: dparo's website
theme: PaperMod
publishdir: ./public/

menu:
  main:
    - identifier: master-thesis
      name: Master Thesis
      url: documents/master-thesis.html

params:
  ananke_socials:
    - name: github
      url: https://github.com/dparo
      label: GitHub Account
