baseURL: http://dparo.github.io
languageCode: en-us
title: dparo's website
theme: PaperMod
publishdir: ./public/

menu:
  main:
    - identifier: ms-degree-dissertation
      name: Dissertation
      url: documents/MSc_Paro_Davide.pdf
    - identifier: msc-presentation
      name: MSc presentation
      url: documents/msc-presentation.pdf

params:
  ananke_socials:
    - name: github
      url: https://github.com/dparo
      label: GitHub Account
